### ISSUE TITLE
Day 3 – Show registrations in a separate page

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/php-bootcamp#9]
## Tasks for day 3

- [ ] Create a new page `registrations.php`.
- [ ] Add header and footer from `index.php` to `registrations.php`.
- [ ] The user should be able to navigate between these pages using the links in the header.
- [ ] Retrieve the registrations stored in the database.
- [ ] Create a bootstrap table to show all the registrations. The columns in the table will be:
    - Serial number
    - Name
    - Phone
- [ ] Create a new registration and verify that the registration table is updated.

## Resources
- [Bootstrap tables](https://getbootstrap.com/docs/4.1/content/tables/)

**Comment by shefali-k** [comment]
- [ ] Create a new page registrations.php.

- [ ]  Add header and footer from index.php to registrations.php.

- [ ] The user should be able to navigate between these pages using the links in the header.

- [ ]  Retrieve the registrations stored in the database.

- [ ]  Create a bootstrap table to show all the registrations. The columns in the table will be:
Serial number
Name
Phone

- [ ] Create a new registration and verify that the registration table is updated.

**Comment by lalitmehta933** [comment]
done
- [ ] Create a new page registrations.php.

- [ ] Add header and footer from index.php to registrations.php.

- [ ] The user should be able to navigate between these pages using the links in the header.

- [ ] Retrieve the registrations stored in the database.

- [ ] Create a bootstrap table to show all the registrations. The columns in the table will be:

- Serial number
- Name
- Phone
- [ ] Create a new registration and verify that the registration table is updated.

**Comment by AkhileshNegi** [comment]
- [ ] -  Create a new page registrations.php.
- [ ] -   Add header and footer from index.php to registrations.php.
- [ ] -   The user should be able to navigate between these pages using the links in the header.
- [ ] -   Retrieve the registrations stored in the database.
- [ ] -   Create a bootstrap table to show all the registrations. The columns in the table will be:

- Serial number
- Name
- Phone

- [ ] -   Create a new registration and verify that the registration table is updated.
